### ISSUE TITLE
RUST编译MSVC 2013缺少`legacy_stdio_definitions.lib`解决办法

### ISSUE THREAD

**Issue by xiaokaixuan** [kaixuan1115/notes#39]
1. 使用自定义链接器`link_wrapper.exe`，链接时忽略`legacy_stdio_definitions.lib`。
```go
// link_wrapper project main.go
package main

import (
	"os"
	"os/exec"
)

var IGNORE_LIBS = map[string]bool{
	"legacy_stdio_definitions.lib": true}

func main() {
	args := []string{}
	for i, str := range os.Args {
		if i == 0 {
			continue
		}
		if !IGNORE_LIBS[str] {
			args = append(args, str)
		}
	}
	pcmd := exec.Command("link.exe", args...)
	pcmd.Stderr = os.Stderr
	pcmd.Stdout = os.Stdout
	pcmd.Run()
}
```
2. `Cargo.toml`同级下创建`.cargo/config.toml`，内容如下，同时将`link_wrapper.exe`放到`.cargo`目录下。
```toml
[target.x86_64-pc-windows-msvc]
linker = ".cargo\\link_wrapper.exe"
rustflags = ["-C", "target-feature=+crt-static"]

[build]
target = "x86_64-pc-windows-msvc"

```
3. `Demo`如下:
[hello.zip](https://github.com/kaixuan1115/notes/files/11514479/hello.zip)
