### ISSUE TITLE
`Cargo`使用代理并忽略`SSL`检查

### ISSUE THREAD

**Issue by xiaokaixuan** [kaixuan1115/notes#40]
创建文件`C:\User\XXX\.cargo/config.toml`，`Linux`下`~/cargo/.config.toml`。内容如下：
```toml
[http]
check-revoke = false
proxy = "127.0.0.1:1080"

```
